Check if list is empty in the pythonic way
containers/podman-py pull request #148
Opened 2021-11-12 14:35 UTC by q0w

1. The pythonic way to do it is from the [PEP 8 style guide](https://www.python.org/dev/peps/pep-0008/):
For sequences, (strings, lists, tuples), use the fact that empty sequences are false:
```python
# Correct:
if not seq:
if seq:
# Wrong:
if len(seq):
if not len(seq):
```

2. Use `[ ]` instead of `list()` (and its faster to initialize)

2021-11-12 14:37 UTC, q0w commented
/assign @baude

2021-11-12 16:16 UTC, rhatdan commented
@mwhahaha @jwhonce PTAL

2021-11-12 16:17 UTC, rhatdan commented
Thanks @q0w 
Looks like gating tests are failing.

2021-11-12 16:46 UTC, jwhonce requested changes
I believe you wanted to use parameter exclude

2021-11-12 16:46 UTC, jwhonce commented on podman/api/tar_utils.py
> +    if not l:
"l" is undefined in this function.

2021-11-12 16:59 UTC, q0w commented on podman/api/tar_utils.py
> +    if not l:
oh, yes, mb

2021-11-12 17:49 UTC, mwhahaha approved these changes
/lgtm

I ran pylint and there's a whole bunch of things to probably fix like this now. it's very unhappy. I might try and tackle that if i get some extra time

2021-11-17 20:46 UTC, jwhonce commented
> /lgtm
> 
> I ran pylint and there's a whole bunch of things to probably fix like this now. it's very unhappy. I might try and tackle that if i get some extra time

I use  "/usr/bin/pylint --msg-template='{abspath}:{line},{column}: {msg} ({symbol})'" --output-format=colorized --max-line-length=100 --disable=fixme --ignore tests podman. Combined with the .pylintrc in the root of the repository. I am curious what you are seeing re: pylint being unhappy. One outstanding issue is to dump the non-compatible API from the repository.

2021-11-17 20:48 UTC, jwhonce approved these changes

2021-11-17 20:48 UTC, merged