[CI:BUILD] Packit: initial enablement
containers/podman-py pull request #242
Opened 2023-02-21 15:29 UTC by lsm5

This commit will run COPR builds on every PR against all active releases of CentOS Stream and Fedora, thus allowing buildability checks before the PR merges.

Builds are done on a custom COPR project:
`rhcontainerbot/packit-builds`.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/

The build targets are set in the copr itself, so we don't need to explicitly mention them in `.packit.yaml`, making upstream configuration a lot simpler.

The `spec.rpkg` file meant for rpm builds post-pr-merge at `rhcontainerbot/podman-next` copr gets reused for packit builds, so the packit jobs are independent of Fedora / CentOS dist-git.

2023-02-21 16:22 UTC, jwhonce requested changes

2023-02-21 16:22 UTC, jwhonce commented on .packit.sh
> +# Update Version in spec with Version from Cargo.toml
```suggestion
# Update Version in spec with Version from version.py
```

2023-02-21 16:22 UTC, jwhonce commented on .packit.yaml
> +      - cargo
```suggestion
      - cargo
```
Is cargo now a dependency?

2023-02-22 12:32 UTC, lsm5 commented on .packit.sh
> +# Update Version in spec with Version from Cargo.toml
copy pasta from aardvark-dns :D

2023-02-22 12:32 UTC, lsm5 commented on .packit.yaml
> +      - cargo
copy pasta from aardvark-dns :D

2023-06-05 20:28 UTC, lsm5 commented
@umohnani8 @rhatdan PTAL

/cc @jwhonce @cevich @edsantiago 

python rpms are `noarch` on fedora and rhel, so I could potentially reduce the number of tasks in the CI, but that would mean complicating the packit config by quite a bit. So, I'd rather keep aarch64 and x86_64 tasks as they are set by default in `rhcontainerbot/packit-builds` copr repo: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/build/6006581/

2023-06-06 10:26 UTC, umohnani8 commented
/lgtm

2023-06-06 10:30 UTC, merged

2023-06-06 11:10 UTC, edsantiago commented
Belated LGTM. Nice work.