rename `working_dir` to `workdir` for consistency
containers/podman-py pull request #332
Opened 2023-09-29 15:15 UTC by aparcar

Currently `podman-py` uses all three versions of `work_dir`, `working_dir` and `workdir` (not to mention `WorkingDir`).

This commit tries to unify the parameter usage by allowing `workdir` for container `create` or `run`. For backwards compatibility `working_dir` still works but a deprecation warning is added.

Since upstream Podman uses a variety of *workdir* versions the `podman-py` codebase can't be simplified further.

Fix: #330

2023-09-29 16:38 UTC, rhatdan commented
LGTM
@umohnani8 @jwhonce @mwhahaha PTAL

2023-09-29 16:45 UTC, umohnani8 commented
Changes LGTM
gating is unhappy due to a format issue https://github.com/containers/podman-py/pull/332/checks?check_run_id=17258548350

2023-09-29 16:52 UTC, jwhonce requested changes

2023-09-29 16:52 UTC, jwhonce commented on podman/domain/containers_create.py
> +
Please remove the warning. The library is intended to be a super set of the Docker SDK which uses `working_dir` as their parameter. I have no issue with workdir being added as an "alias".

2023-09-29 16:52 UTC, jwhonce commented on podman/domain/containers_create.py
> -            working_dir (str): Path to the working directory.
Please retain this comment, see below.

2023-09-29 16:52 UTC, jwhonce commented on podman/tests/integration/test_container_create.py
> +
Thank you for including a test, but it will need to be adjusted to verify `workdir` works as expected.

2023-11-12 12:06 UTC, rhatdan commented
@aparcar still working on this?

2024-01-22 16:10 UTC, rhatdan commented
@umohnani8 Could you take this over and get it merged?

2024-01-22 17:04 UTC, closed without merging