Clean up code, list containers
containers/podman-py pull request #38
Opened 2020-11-05 22:51 UTC by jwhonce

* Reformat project with black formatter/style + isort
* Rename __ALL__ to __all__
* Implement list_containers() + unit tests

Signed-off-by: Jhon Honce <jhonce@redhat.com>

2020-11-05 22:52 UTC, jwhonce commented
@mwhahaha PTAL

2020-11-05 23:18 UTC, mwhahaha commented on podman/tests/unit/test_api_connection.py
> +                          'x':            'y',
Was this a magical formatter thing?

2020-11-05 23:18 UTC, mwhahaha approved these changes
looks fine

2020-11-05 23:30 UTC, mwhahaha requested changes

2020-11-05 23:30 UTC, mwhahaha commented on podman/containers/__init__.py
> +def list_containers(api, all=None):
actually all is a built-in in python

2020-11-05 23:30 UTC, mwhahaha commented on podman/tests/unit/containers/test_containers.py
> +        self.request.assert_called_once_with('/containers/json')
This is failing (i need to fix the makefile as it's not exiting on failure anymore). 

```
AssertionError: Expected call: get('/containers/json')
Actual call: get('/containers/json', {})
```

2020-11-06 16:29 UTC, jwhonce commented on podman/tests/unit/test_api_connection.py
> +                          'x':            'y',
Yeah, not my favorite.

2020-11-06 17:06 UTC, TomSweeneyRedHat commented on podman/images/__init__.py
> +    Name may also be a image ID.
nit of a nit, only change if you've other tweaks.
```suggestion
    Name may also be an image ID.
```

2020-11-06 17:10 UTC, jwhonce commented
@mwhahaha: r+

2020-11-06 17:10 UTC, TomSweeneyRedHat commented on podman/images/__init__.py
> +    Name may also be a image ID.
Actually, this is user-facing, can you clean this and I'll LGTM it?

2020-11-06 17:25 UTC, mwhahaha commented on podman/api_connection.py
> +        self, url, base="/v1.24/libpod", *args, **kwargs
pylint seems unhappy with this for whatever reason, but we can resolve that later in the black usage patch.

2020-11-06 17:26 UTC, mwhahaha approved these changes
LGTM

2020-11-06 17:26 UTC, mwhahaha commented
bors r+

2020-11-06 17:29 UTC, mwhahaha commented
bors r+

2020-11-06 17:30 UTC, merged