fix: Enhance environment connection error handling
containers/podman-py pull request #472
Opened 2024-11-23 18:10 UTC by Mr-Sunglasses

fix: #455 

Add `PodmanConnectionError` to improve debugging of connection failures when 
initializing client from environment variables. The new error provides:

- Detailed error messages with connection host and environment state
- Preservation of original exception information
- Better context for common failure modes (invalid config, connection failures)

Previously, raw exceptions from connection attempts could be confusing to 
diagnose, especially when involving environment variables. This change makes it
clearer what went wrong during client initialization.

2024-11-25 12:48 UTC, inknos requested changes
It would be nice to test these exceptions if possible.

I'll give you an idea of what I was thinking to test it.

What do you think? :)

```diff
--- a/podman/tests/integration/test_system.py
+++ b/podman/tests/integration/test_system.py
@@ -64,3 +64,10 @@ class SystemIntegrationTest(base.IntegrationTest):
     def test_from_env(self):
         """integration: from_env() no error"""
         PodmanClient.from_env()
+
+    def test_from_env_exceptions(self):
+        """integration: from_env() returns exceptions"""
+        with self.assertRaises(PodmanConnectionError):
+            PodmanClient.from_env(base_url="unix:///path/to/nonexistent.sock")
```

2024-11-25 12:48 UTC, inknos commented on podman/client.py
For code clarity, I would prefer to use python's exception handling here.

```
except ValueError as e:
    error_msg = "Invalid environment configuration for Podman client"
    raise PodmanConnectionError(
        message=error_msg, environment=environment, host=host, original_error=e)
except (ConnectionError, TimeoutError) as e:
    error_msg = "Failed to connect to Podman service"
    raise PodmanConnectionError(
         message=error_msg, environment=environment, host=host, original_error=e)
except Exception as e:
    error_msg = "Failed to initialize Podman client from environment"
    raise PodmanConnectionError(
         message=error_msg, environment=environment, host=host, original_error=e)
```

I would avoid filtering exceptions with if conditions in the except block, unless you have a strong reason to do so.

2024-12-19 01:23 UTC, D3vil0p3r commented
Any news on this PR?

2024-12-19 01:24 UTC, D3vil0p3r commented
@Mr-Sunglasses Any news on this PR?

2025-01-15 15:28 UTC, D3vil0p3r commented
@Mr-Sunglasses any news on this PR?

2025-02-03 19:25 UTC, Mr-Sunglasses commented
> @Mr-Sunglasses any news on this PR?

Thanks a lot @D3vil0p3r , I got it where we need to fix, I will submit a patch ASAP 😄

2025-02-15 12:48 UTC, D3vil0p3r commented
> > @Mr-Sunglasses any news on this PR?
> 
> Thanks a lot @D3vil0p3r , I got it where we need to fix, I will submit a patch ASAP 😄

Hey mate! Any news about it?

2025-02-16 16:23 UTC, Mr-Sunglasses commented
> > > @Mr-Sunglasses any news on this PR?
> > 
> > 
> > Thanks a lot @D3vil0p3r , I got it where we need to fix, I will submit a patch ASAP 😄
> 
> Hey mate! Any news about it?

Thanks a lot @D3vil0p3r for pinging me, I forgot about this PR. I have does the necessary changes in this PR: #512 because the current PR is messed up, and also thanks a lot for your help, It really make it easy for me to solve the issue, Thanks mate 🙏🏻.

2025-02-16 16:25 UTC, D3vil0p3r commented
I thank you for your commitment. I appreciate a lot.

2025-02-17 14:35 UTC, inknos commented
if I understand it right, I am closing this in favor of https://github.com/containers/podman-py/pull/512 :)

2025-02-17 14:35 UTC, closed without merging